name: CI/CD - .NET 8 Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

     
